# Generated by Django 2.0.1 on 2018-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0002_remove_contact_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
