# Generated by Django 2.0.1 on 2018-01-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_auto_20180114_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
