# Generated by Django 2.0.1 on 2018-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
