# Generated by Django 2.0.1 on 2018-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog', '0009_auto_20180122_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('article', 'article'), ('tip', 'tip'), ('snippet', 'snippet')], default='article', max_length=10, null=True),
        ),
    ]
